//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Surf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bungalow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bungalow()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int NumBung { get; set; }
        public string TipBung { get; set; }
        public decimal PrecoBung { get; set; }
        public bool Reservado { get; set; }
        public Nullable<int> NumCamas { get; set; }
        public Nullable<int> NumPessoas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
